
 
name: Building wsa

on:


  workflow_dispatch:
  

  

jobs:

  build:

    runs-on: ubuntu-latest 

    steps:

       - name: Init the System

         uses: actions/checkout@master
  
       - name: Install Git and other requirements 

         run: |
            sudo apt update && sudo apt install git
            sudo apt install lzip patchelf e2fsprogs python3 aria2 attr unzip qemu-utils 

        
       - name: Clone And Build

         run: |
          git clone https://github.com/Hasajapathirana/MagiskOnWSALocal.git --depth 1
          cd MagiskOnWSALocal
          sudo apt install e2fsprogs
          ./scripts/build.sh --arch x64 --release-type RP --magisk-ver stable --gapps-variant pico --remove-amazon --compress-format 7z

       - name: Save
         uses: actions/upload-artifact@v2
         with:
            name: WSA_Build
            path: /home/runner/work/WSA_builder/WSA_builder/MagiskOnWSALocal/output/*WSA*
            retention-days: 31


  
          

          

