
 
name: Building Windows Subsytem for Android

on:


  workflow_dispatch:
  

  

jobs:

  build:

    runs-on: ubuntu-latest 

    steps:

       - name: Init the System

         uses: actions/checkout@master
  
       - name: Install Git and other requirements 

         run: |
            echo "installing dependencies"
            sudo apt update && sudo apt install git
            sudo apt install lzip patchelf e2fsprogs python3 aria2 attr unzip qemu-utils 
            echo "installing completed"
        
       - name: Clone And Build

         run: |
          echo "syncing the repo"
          git clone https://github.com/Hasajapathirana/MagiskOnWSALocal.git --depth 1
          echo "sync completed"
          cd MagiskOnWSALocal
          echo ""starting build"
          ./scripts/build.sh --arch x64 --release-type retail --root-sol magisk --magisk-ver stable --install-gapps --compress-format 7z
          echo "building completed"
          
       - name: Save
         uses: actions/upload-artifact@v2
         with:
            name: WSA_Build
            path: /home/runner/work/WSA_builder/WSA_builder/MagiskOnWSALocal/output/*WSA*
            retention-days: 31


  
          

          

