
 
name: Building wsa

on:


  workflow_dispatch:
  

  

jobs:

  build:

    runs-on: ubuntu-latest 

    steps:

       - name: Init the System

         uses: actions/checkout@master

   
    
    
  
       - name: Install Git and other requirements 

         run: |
            sudo apt update && sudo apt install git
            sudo apt install lzip patchelf e2fsprogs python3 aria2 attr unzip qemu-utils 

        
       - name: Clone And Build

         run: |
          git clone https://github.com/Hasajapathirana/MagiskOnWSALocal.git --depth 1
          cd MagiskOnWSALocal
          sudo apt install e2fsprogs
          ./scripts/build.sh --compress-format zip

            

       - name: Save
         uses: actions/upload-artifact@v2
         with:
            name: Windows Subsystem For android
            path: /home/runner/work/WSA_builder/WSA_builder/MagiskOnWSALocal/output/*WSA*
            retention-days: 31


      
       - name: Release recovery
         uses: softprops/action-gh-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          tag_name: ${{ github.run_id }}
          name: Windows Subsystem For android
          files: /home/runner/work/WSA_builder/WSA_builder/MagiskOnWSALocal/output/*WSA*
          retention-days: 90

  
          

          

